version: "3"

services:

 ms-sql-server:
  image: mcr.microsoft.com/mssql/server:2019-latest
  environment:
   ACCEPT_EULA:"Y"
   SA_PASSWORD:"123456"
   MSSQL_PID: Developer
  ports:
   - "1433:1433"
 